apiVersion: apps/v1
kind: Deployment
metadata:
  name: n0fitication
  labels:
    app: n0fitication
spec:
  replicas: 1
  template:
    metadata:
      name: n0fitication
      labels:
        app: n0fitication
    spec:
      containers:
        - name: n0fitication
          image: joacobnd/n0tification:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
      restartPolicy: Always
  selector:
    matchLabels:
      app: n0fitication
